version: '{build}'

init:
  - cmd: git config --global core.autocrlf true

image:
  - Visual Studio 2017
  - Ubuntu

skip_commits:
  files:
    - docs/*
    - .github/*
    - logo/*
    - '**/*.md'

environment:
  NUGET_API_KEY:
    secure: UHweOfsSUq1apwinPBbBuxw/yW+Q6DhikKofkACtOTt2kDESEbL9jtpEkfn7fxOM

build_script:
- pwsh: .\scripts\ServerBuild.ps1

test: off

artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet